CONFIG_ZMK_SLEEP=y
# Włącza obsługę USB
CONFIG_ZMK_USB=y
# Włącza obsługę Bluetooth
CONFIG_ZMK_BLE=y
# Nazwa wyświetlana w Windows
CONFIG_ZMK_KEYBOARD_NAME="QUAD KEY"
CONFIG_ZMK_USB_LOGGING=y
# Wymusza obsługę zapisu ustawień w pamięci flash
CONFIG_SETTINGS=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# To jest kluczowe: jeśli flash jest uszkodzony, ZMK spróbuje go sformatować
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
